import org.gradle.internal.os.OperatingSystem

plugins {
    alias(libs.plugins.kotlinJvm)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.graalvmNative)
    application
}

/**
 * The version, compiled in rather than typed twice.
 *
 * `--version` used to be a string literal in `Main.kt`, which meant a tagged release shipped four
 * numbers that could disagree: the binary's, the `.deb`'s `Version:`, the container tag and the
 * GitHub release. Installing `loopky_0.2.0_amd64.deb` and being told `loopky 0.1.0` is the first
 * thing a new user sees, because `install.sh` ends by running `--version` (#210).
 *
 * One number, in `gradle.properties`, and the release workflow refuses a tag that disagrees with
 * it. Generated Kotlin rather than a resource so it is compile-time and needs no reachability
 * registration in the native image.
 */
val cliVersion: String = providers.gradleProperty("loopkyCliVersion").get()

val generateCliVersion = tasks.register("generateCliVersion") {
    val version = cliVersion
    val outputDir = layout.buildDirectory.dir("generated/version")
    outputs.dir(outputDir)
    inputs.property("version", version)
    doLast {
        val file = outputDir.get().asFile.resolve("com/github/jvsena42/loopky/cli/BuildVersion.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            // Generated by :cli:generateCliVersion from `loopkyCliVersion` in gradle.properties.
            package com.github.jvsena42.loopky.cli

            internal const val CLI_VERSION = "$version"

            """.trimIndent(),
        )
    }
}

/**
 * `loopky` — the headless client (#54).
 *
 * A plain JVM module rather than another KMP target: it consumes `:shared`'s `jvm()` variant and
 * has no platform half of its own. It reaches for repositories directly and never touches
 * `presentation/`, which is what the repos-own-the-logic rule (no use-case layer) buys here.
 */
kotlin {
    jvmToolchain(17)
    sourceSets.main { kotlin.srcDir(generateCliVersion) }
}

dependencies {
    implementation(projects.shared)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.koin.core)
    // QR encoding for `loopky login`. Already in the catalog for the tablet sign-in panel; core
    // only, so it brings no camera/scanner stack.
    implementation(libs.zxing.core)
    // Directly, for one call: `RustLog.kt` sets `RUST_LOG` through libc, which is the only way a
    // binary with no start script can default it. JNA is already on the runtime classpath via
    // `:shared`'s FFI bindings — this makes the compile-time dependency honest rather than
    // borrowed from a transitive `implementation`.
    implementation(libs.jna)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.kotlinx.coroutines.test)
}

application {
    applicationName = "loopky"
    mainClass.set("com.github.jvsena42.loopky.cli.MainKt")
    // ImageIO's raster and JPEG paths need no display, but AWT tries to open one on first use
    // unless told otherwise — an exception rather than a fallback on a box with no X server.
    // `JvmMediaProcessor` degrades either way; this stops it having to.
    applicationDefaultJvmArgs = listOf("-Djava.awt.headless=true")
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}

/**
 * Quiet the pubky SDK's own `tracing` output unless the user asks for it.
 *
 * `libpubkycore` installs a subscriber that, with no `RUST_LOG` set, defaults to
 * `pubky=info,pubkycore=debug` and writes ANSI-coloured lines to stderr — four of them before a
 * `login` has printed anything. It is genuinely useful when a relay or a TLS handshake is
 * misbehaving and pure noise the rest of the time.
 *
 * It has to be an environment variable, and it has to be set before the library loads: the filter
 * is read once, from the process environment, by a `Lazy` the first network call triggers. A JVM
 * cannot set its own environment, so the start script is the only place this can happen — which is
 * also why it is a default rather than an override: `RUST_LOG=debug loopky …` still works, and is
 * the first thing to try when a homeserver call fails for no visible reason.
 */
tasks.named<CreateStartScripts>("startScripts") {
    doLast {
        unixScript.writeText(
            unixScript.readText().replace(
                "\nAPP_HOME=",
                "\nexport RUST_LOG=\"\${RUST_LOG:-warn}\"\n\nAPP_HOME=",
            ),
        )
        windowsScript.writeText(
            windowsScript.readText().replace(
                "\r\nset APP_HOME=",
                "\r\nif not defined RUST_LOG set RUST_LOG=warn\r\nset APP_HOME=",
            ),
        )
    }
}

/**
 * A native row: the directory JNA looks a library up under, and the files it expects to find
 * there. Mirrors the table in `shared/src/jvmMain/resources/README.md` — the two halves of this
 * build have to agree on that layout or nothing links against anything.
 *
 * [distribution] is the Gradle distribution name, which is also the tarball's: `loopky-linux` and
 * `loopky-macos` are what a person types, not `loopky-linux-x86-64`.
 */
data class NativeRow(
    val jnaPrefix: String,
    val distribution: String,
    val pubkyLib: String,
    val jnaLib: String,
    val sqliteDir: String,
)

val nativeRows = listOf(
    NativeRow("linux-x86-64", "linux", "libpubkycore.so", "libjnidispatch.so", "Linux/x86_64"),
    NativeRow("darwin-aarch64", "macos", "libpubkycore.dylib", "libjnidispatch.jnilib", "Mac/aarch64"),
    // No `lib` prefix on either native name, which is what JNA and sqlite-jdbc both expect on
    // Windows: `com/sun/jna/win32-x86-64/jnidispatch.dll` and `org/sqlite/native/Windows/x86_64/`.
    NativeRow("win32-x86-64", "windows", "pubkycore.dll", "jnidispatch.dll", "Windows/x86_64"),
)

/**
 * The row this machine can build a *binary* for, or null.
 *
 * `native-image` does not cross-compile: the host **is** the target. That is why the release
 * workflow runs one job per row rather than one job with a matrix of flags, and why the Linux
 * binary is built inside a container even on a Linux runner — the glibc it links against is the
 * builder's, and `libpubkycore.so` already needs 2.34.
 *
 * The *jar* distributions below have no such restriction and are built for both rows from either
 * host, which is the whole reason they are still worth having.
 */
val hostNativeRow: NativeRow? = run {
    val os = OperatingSystem.current()
    val arch = System.getProperty("os.arch")
    when {
        os.isLinux && (arch == "amd64" || arch == "x86_64") -> nativeRows[0]
        os.isMacOsX && arch == "aarch64" -> nativeRows[1]
        os.isWindows && (arch == "amd64" || arch == "x86_64") -> nativeRows[2]
        else -> null
    }
}

/**
 * `loopky` as a single self-contained binary (#210).
 *
 * The install story #54 called "the primary constraint" is a one-line `curl` into a cloud agent's
 * sandbox: non-root, ephemeral, configured by a setup script. "Install a JDK" is exactly what that
 * cannot be, and a jar plus a start script needs one. So: `native-image`, ~20-40 ms of start-up
 * against the JVM's ~200, and nothing on the target machine.
 *
 * **JNA is the whole of the difficulty**, and worth being precise about why. `libpubkycore` ships
 * *inside the jar* under JNA's resource layout and `Native.load` extracts it to a temp file at
 * runtime — reflective resource loading, which is the one thing a closed-world image has to be
 * told about explicitly. Three separate registrations carry it, all in
 * `src/main/resources/META-INF/native-image/`:
 *
 * - the `.so`/`.dylib` itself as an embedded **resource**, so there is something to extract;
 * - JNA's `Structure` subclasses and `Callback` interfaces for **reflection**, because JNA reads
 *   their fields and synthesises their implementations;
 * - `_UniFFILib` as a **dynamic proxy**, which is what `Native.load(name, Interface::class.java)`
 *   actually returns.
 *
 * Everything else here is ordinary: kotlinx.serialization is compile-time, Koin's DSL is explicit
 * constructor calls rather than reflection, and the CLI has no classpath scanning anywhere.
 */
graalvmNative {
    // The plugin's toolchain search wants a GraalVM registered as a Java toolchain; this build
    // pins `jvmToolchain(17)` for compilation and takes the image builder from `GRAALVM_HOME`
    // (falling back to `JAVA_HOME`) instead, which is what both the release workflow and a
    // developer with a downloaded GraalVM already have set.
    toolchainDetection.set(false)

    // **Off, and that is a decision.** The community metadata repository is the usual answer for
    // JNA, but its rows are per-library and applied wholesale, and switching it on here pulled
    // `java.awt` into the image — which on Linux is not a size problem but a *shape* problem: the
    // build then emits `libawt.so`, `libawt_headless.so` and `libawt_xawt.so` beside the binary
    // and `loopky` stops being one file. Its JNA rows turned out to be a subset of what the
    // tracing agent had already recorded from a real FFI run, so the only thing lost was
    // `com.sun.jna.NativeLong`, now merged into `reflect-config.json`. See the README beside it.
    //
    // A build that fetches nothing is the other half of the trade: the release image is produced
    // from this repository and a GraalVM tarball, and nothing else.
    metadataRepository { enabled.set(false) }

    binaries.named("main") {
        imageName.set("loopky")
        mainClass.set("com.github.jvsena42.loopky.cli.MainKt")
        // Every reflective access is registered, so a fallback image — a binary that silently
        // ships a JVM inside itself — is a build failure rather than a shipped surprise.
        fallback.set(false)
        buildArgs.addAll(nativeBuildArgs())
    }

    // The image builder is a long-running JVM; without this the plugin also builds a test image.
    binaries.all { verbose.set(false) }
}

/**
 * The `native-image` arguments, split out so the reasoning fits beside each one.
 *
 * Empty for a host with no row, which is *not* the same as "build it anyway": that combination is
 * refused by [checkNativeImageHostIsSupported] before the image builder runs. Without that check
 * an unshipped host builds happily and emits exactly one file — with no `libpubkycore` embedded,
 * no `libjnidispatch`, and no URL protocol handlers — and `checkNativeImageIsOneFile` passes,
 * because it *is* one file.
 */
fun nativeBuildArgs(): List<String> {
    val row = hostNativeRow ?: return emptyList()
    return listOf(
        // `HttpURLConnection` over TLS is how `JvmHttpFetcher` reaches Nexus and the Homegate.
        // Native images ship no URL protocol handlers unless asked, and the failure is a
        // `MalformedURLException` at the first read rather than anything about TLS.
        "--enable-url-protocols=http,https",
        // The three native rows that have to survive into the image, all extracted at runtime by
        // a loader that reads them off the classpath.
        // **No `Regex.escape` here, and that is a Windows bug rather than a tidy-up** (#301).
        // It emits `\Q…\E`, and those backslashes do not survive the trip to `native-image.exe`:
        // the Windows build received `\\Qwin32-x86-64\\E/\\Qjnidispatch.dll\\E`, which is a literal
        // `\Q…` rather than a quote block, so both patterns matched nothing. Neither library was
        // embedded, `com.sun.jna.NativeLibrary` failed to initialise, and every
        // `Function.getFunction` after it died — surfacing as `StdoutGuard` refusing `--json`.
        // The two patterns below carry no backslashes and were unaffected, which is the tell.
        //
        // Nothing needs escaping: `.` is the only regex-special character in these names and it
        // matches the literal dot it stands for.
        "-H:IncludeResources=${row.jnaPrefix}/${row.pubkyLib}",
        "-H:IncludeResources=com/sun/jna/${row.jnaPrefix}/${row.jnaLib}",
        "-H:IncludeResources=org/sqlite/native/${row.sqliteDir}/.*",
        // `ServiceLoader` files: the SQLite JDBC driver registers itself through one, and the
        // `.apkg` reader opens its collection through `DriverManager`.
        "-H:IncludeResources=META-INF/services/.*",
        // A deck's text is whatever its author pasted. The default image carries Latin-1 and
        // UTF-8 only, and a `--separator` or an `.apkg` in another encoding would decode to
        // mojibake rather than fail.
        "-H:+AddAllCharsets",
        // Names in stack traces, so an `--verbose` report from a user's machine is readable.
        "-H:+UnlockExperimentalVMOptions",
        "-H:-ReduceImplicitExceptionStackTraceInformation",
        // JNA calls `System.load`, which JDK 24 made a restricted method: without this the binary
        // prints four `WARNING: A restricted method …` lines to stderr before it prints anything
        // of its own. Exactly the noise the jar's start script exists to suppress, arriving by a
        // different door, on the channel an agent harness captures into its transcript.
        "--enable-native-access=ALL-UNNAMED",
        // Baseline x86-64 rather than `native-image`'s x86-64-v3 default. A binary compiled for
        // v3 needs AVX2 and dies with SIGILL on a host without it — and this one is *downloaded*,
        // onto a sandbox whose CPU nobody chose. Irrelevant to a client that spends its life
        // waiting on a homeserver.
        // Gated on the *architecture*, not the OS. The reason above is about x86-64 microarchitecture
        // levels and a downloaded binary meeting a CPU nobody chose, which is as true of
        // `win32-x86-64` as of `linux-x86-64`; `darwin-aarch64` is the only row it cannot apply to.
        // Reading this as a Linux concern is what left Windows on the v3 default (#301).
        *(if (row.jnaPrefix.endsWith("x86-64")) arrayOf("-march=compatibility") else emptyArray()),
        // **Attempting a static CRT on Windows, and it may not work** (#301). The image imports
        // `VCRUNTIME140.dll` and `VCRUNTIME140_1.dll` — the only two of its 23 imports that are not
        // in-box on Windows 10+, since the `api-ms-win-crt-*` entries are the Universal CRT — so a
        // downloaded `loopky.exe` will not start without the Visual C++ redistributable.
        //
        // GraalVM 25.0.2 offers no static-CRT switch here: `--static` and
        // `-H:+StaticExecutableWithDynamicLibC` are Linux-only, and probing `--help-extra` and
        // `--expert-options-all` on the runner returned nothing matching static, libc or linker.
        // `/MT` goes straight to the linker instead. The expected failure is duplicate or missing
        // symbols, because GraalVM's own Windows JDK static libraries are built against the
        // dynamic CRT — if that happens, the answer is to accept the dependency and pin the import
        // set so a *new* one still fails the build, rather than to relax the check.
        *(if (row.jnaPrefix.startsWith("win32")) arrayOf("-H:NativeLinkerOption=/MT") else emptyArray()),
    )
}

/**
 * The binary has to be **one file**, and this is what says so out loud.
 *
 * A `native-image` build does not fail when it cannot fold a JDK native library into the
 * executable — it emits the library *beside* it and reports success. Reaching `javax.imageio` from
 * anywhere pulls in `java.awt`, and on Linux that turns the output into eight files:
 * `libawt.so`, `libawt_headless.so`, `libawt_xawt.so`, `libjavajpeg.so`, `liblcms.so`,
 * `libjava.so`, `libjvm.so` and `loopky`. The build stays green, the tests stay green, and the
 * one-line `curl … -o ~/.local/bin/loopky` install this whole issue exists for is quietly dead.
 *
 * It has already happened twice in one sitting — the QR PNG writer and the Koin binding for
 * `MediaProcessor` — so it is checked rather than remembered. The two fixes are in
 * `TerminalQr.toPng` and `PassThroughMediaProcessor`; the way to find the third is
 * `-H:AbortOnTypeReachable=java.awt.image.BufferedImage`, which prints the call path that reached
 * it.
 */
/**
 * Refuse to build a binary for a host there is no `libpubkycore` row for.
 *
 * A task rather than an `error(…)` at configuration time, because configuration failing would
 * take `:cli:test` and `:cli:installDist` down with it — and those are perfectly buildable on a
 * host that cannot produce a *binary*. `native-image` does not cross-compile, so this is the same
 * matrix `SupportedHost` refuses at runtime, enforced one step earlier for the one artifact where
 * the mistake is unrecoverable: an image with no FFI in it looks exactly like a good one.
 */
val checkNativeImageHostIsSupported = tasks.register("checkNativeImageHostIsSupported") {
    group = "verification"
    description = "Fails if this host has no libpubkycore row to embed."
    val row = hostNativeRow
    val host = "${OperatingSystem.current().name} ${System.getProperty("os.arch")}"
    val shipped = nativeRows.joinToString(" and ") { it.jnaPrefix }
    doLast {
        checkNotNull(row) {
            "no libpubkycore row for $host, so a native binary built here would have no FFI and " +
                "no HTTPS in it — and would still be exactly one file. The rows are $shipped. " +
                "`native-image` does not cross-compile; build on the host you are targeting, or " +
                "use `./gradlew :cli:installDist`, which runs anywhere a JRE 17 does."
        }
    }
}

val checkNativeImageIsOneFile = tasks.register("checkNativeImageIsOneFile") {
    group = "verification"
    description = "Fails if `nativeCompile` emitted anything beside the binary."
    val outputDir = layout.buildDirectory.dir("native/nativeCompile")
    // `loopky.exe` on Windows, and derived from the host row rather than spelled a second time:
    // the check filtered on the literal `loopky`, so on that row it counted the binary itself as a
    // stray and failed every build (#301). Deliberately **not** widened to tolerate a `.pdb` or a
    // `reports/` — whether `native-image` emits anything else there is unmeasured, and a filter
    // loosened in advance would hide the answer rather than produce it.
    val binaryName = if (hostNativeRow?.jnaPrefix?.startsWith("win32") == true) "loopky.exe" else "loopky"
    doLast {
        // Every entry, not just `isFile`. A stray *directory* — `reports/`, which a diagnostic
        // flag produces — used to pass here and then fail CI's `ls | wc -l` instead, which is a
        // bare exit code with none of the explanation below.
        val strays = outputDir.get().asFile.listFiles().orEmpty()
            .filter { it.name != binaryName }
            .map { if (it.isDirectory) "${it.name}/" else it.name }
            .sorted()
        check(strays.isEmpty()) {
            "native-image emitted ${strays.size} entr(y/ies) beside the binary: " +
                "${strays.joinToString()}. `loopky` is installed by copying one file, so " +
                "something now reachable needs a JDK native library — AWT via javax.imageio is " +
                "the usual cause. Find it with -H:AbortOnTypeReachable=<type>. A trailing `/` is " +
                "a directory, which usually means a diagnostic flag is still set."
        }
    }
}

tasks.matching { it.name == "nativeCompile" }.configureEach {
    dependsOn(checkNativeImageHostIsSupported)
    finalizedBy(checkNativeImageIsOneFile)
    // Clear the output directory first, so the check above sees this build's artifacts and not a
    // previous one's. Without it a run that once emitted `libawt_xawt.so` leaves the file behind,
    // `nativeCompile` never removes it, and the check goes on failing — blaming code that has
    // already been fixed — until somebody runs `clean`.
    val outputDir = layout.buildDirectory.dir("native/nativeCompile").get().asFile
    doFirst { outputDir.deleteRecursively() }
}

/**
 * `:shared`'s desktop jar as the generated start script's `CLASSPATH` spells it.
 *
 * No version in the name because `:shared` declares none, which is what lets a repacked copy stand
 * in for it. If a version is ever set, both uses below stop matching — silently, producing a
 * tarball with two shared jars in it.
 */
val sharedJvmJarName = "shared-jvm.jar"

/**
 * The jar distributions, one per native row rather than one carrying both (#210).
 *
 * `distTar` ships `shared-jvm.jar`, and that jar holds **every** row's `libpubkycore` because
 * shipping the library inside the jar is what means nobody installs one by hand
 * (`shared/src/jvmMain/resources/README.md`). Fine for the jar; wrong for a tarball, where a Linux
 * box hauls 11 MB of macOS dylib it can never load. So each distribution gets a repacked copy of
 * that jar with the other rows dropped — same filename, so the generated start script's
 * `CLASSPATH` still resolves.
 *
 * These are the *portable* artifact, and the reason to keep them: they need a JRE 17, but they are
 * built for either row from either host, where a binary cannot be. `installDist` is unchanged and
 * still carries both, because it is the developer's build and cross-row is the point there.
 */
nativeRows.forEach { row ->
    // Locals, not the script-level properties: a lambda that reads one of those captures the
    // script object itself, which the configuration cache refuses to serialize.
    val jarName = sharedJvmJarName
    val foreignRows = nativeRows.filter { it != row }.map { "${it.jnaPrefix}/**" }

    val repacked = tasks.register<Jar>("sharedJar${row.distribution.replaceFirstChar(Char::uppercase)}") {
        description = "shared-jvm.jar with every native row but ${row.jnaPrefix} removed."
        // The jar comes out of the runtime classpath rather than by reaching into `:shared`'s
        // task graph, so this needs the dependency stated: `zipTree(provider)` reads the file, it
        // does not carry the producer with it.
        dependsOn(configurations.runtimeClasspath)
        archiveFileName.set(jarName)
        destinationDirectory.set(layout.buildDirectory.dir("nativeRows/${row.jnaPrefix}"))
        from(
            zipTree(
                configurations.runtimeClasspath.map { cp ->
                    // By exact filename, so say so when it stops being that name. `:shared`'s
                    // Android plugin swap (#273) left the jvm() artifact alone, but a silent
                    // `first {}` failure here would look like a native-row bug rather than a
                    // renamed jar.
                    cp.firstOrNull { it.name == jarName }
                        ?: error(
                            "$jarName is not on :cli's runtime classpath — :shared's jvm() " +
                                "artifact was renamed. Found: ${cp.joinToString { it.name }}",
                        )
                },
            ),
        )
        exclude(foreignRows)
    }

    distributions.create(row.distribution) {
        distributionBaseName.set("loopky-${row.jnaPrefix}")
        contents {
            into("bin") {
                from(tasks.named("startScripts"))
                filePermissions { unix("rwxr-xr-x") }
            }
            into("lib") {
                from(tasks.named("jar"))
                // Everything except the fat shared jar, which the repacked one replaces under the
                // same name — the start script's CLASSPATH lists jars by name.
                from(configurations.runtimeClasspath.map { cp -> cp.filter { it.name != jarName } })
                from(repacked)
            }
        }
    }
}
