http_port 3128
auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/htpasswd
acl authed proxy_auth REQUIRED
acl allowed dstdomain "/etc/squid/allowlist.txt"
http_access deny !authed
http_access allow CONNECT allowed
http_access allow allowed
http_access deny all
reply_header_add X-Deny-Reason "host_not_allowed" !allowed
access_log daemon:/var/log/squid/access.log squid
cache deny all
