#!/bin/sh
#
# Build a `.deb` around an already-built Linux binary.
#
#   cli/packaging/deb.sh cli/build/native/linux-x86-64/loopky 0.1.0 out/
#
# **A file on the Releases page, and no hosted apt repository.** Adding a third-party apt repo is
# four privileged commands and a GPG keyring on a machine that may not have root, where the same
# binary is one `curl` and needs none (#54). The `.deb` is here for the people whose fleet is
# managed by a package manager and who would rather `dpkg -i` than curl, not as the recommended
# path.
set -eu

BINARY="${1:?usage: deb.sh <binary> <version> <outdir>}"
VERSION="${2:?usage: deb.sh <binary> <version> <outdir>}"
OUTDIR="${3:?usage: deb.sh <binary> <version> <outdir>}"

# Debian rejects a leading `v`, and the tag has one.
VERSION="${VERSION#v}"

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT INT TERM

mkdir -p "$STAGE/DEBIAN" "$STAGE/usr/bin" "$STAGE/usr/share/doc/loopky"
install -m 0755 "$BINARY" "$STAGE/usr/bin/loopky"
install -m 0644 cli/README.md "$STAGE/usr/share/doc/loopky/README.md"

# Shell completions, in the directories each shell already searches — so `dpkg -i` is the whole of
# the setup and no rc file is edited.
#
# **Generated by running the binary being packaged**, not copied from the tree. The scripts
# describe the command surface of one specific build, and a checked-in copy would drift the first
# time a flag is added, in the direction nobody notices: a completion that offers a flag which is
# refused. This is the same host that just built the binary, so it can run it.
mkdir -p "$STAGE/usr/share/bash-completion/completions" \
    "$STAGE/usr/share/zsh/vendor-completions" \
    "$STAGE/usr/share/fish/vendor_completions.d"
"$BINARY" completion bash > "$STAGE/usr/share/bash-completion/completions/loopky"
"$BINARY" completion zsh > "$STAGE/usr/share/zsh/vendor-completions/_loopky"
"$BINARY" completion fish > "$STAGE/usr/share/fish/vendor_completions.d/loopky.fish"
chmod 0644 "$STAGE/usr/share/bash-completion/completions/loopky" \
    "$STAGE/usr/share/zsh/vendor-completions/_loopky" \
    "$STAGE/usr/share/fish/vendor_completions.d/loopky.fish"

# **No JRE, and the two libraries there really are.** `ldd` on the binary reports `libz.so.1`,
# `libc.so.6` and the loader, and nothing else — no JVM, no JNI stubs. That is the claim this
# package exists to make, and stating the two real dependencies does not weaken it.
#
# The `libc6 (>= 2.34)` bound is load-bearing rather than tidy. The floor is `libpubkycore.so`'s,
# not ours, and without the bound `dpkg -i` on an older release **succeeds** — then the binary
# dies at exec with `/lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found`, a raw
# loader error naming no package and no fix. That is the same misdiagnosis `SupportedHost` and
# exit code 10 exist to prevent, one layer down; with the bound, dpkg refuses up front and says
# which package is too old.
#
# `zlib1g` unversioned on purpose: the binary needs `ZLIB_1.2.2`, which predates every release
# that could satisfy the libc bound anyway, and pinning it would mean guessing at the epoch
# Debian carries on that package.
cat > "$STAGE/DEBIAN/control" <<CONTROL
Package: loopky
Version: $VERSION
Section: utils
Priority: optional
Architecture: amd64
Depends: libc6 (>= 2.34), zlib1g
Maintainer: Loopky <https://github.com/jvsena42/loopky>
Homepage: https://github.com/jvsena42/loopky
Description: Headless Loopky client for creating and managing flashcard decks
 loopky is a terminal client for Loopky, a Pubky-backed flashcards app. It exists so an
 agent can create and manage decks without a phone screen: every command takes --json,
 and the exit code is the primary result.
 .
 A single self-contained binary. No JRE is required: it links only against libc and
 zlib. The glibc 2.34 floor is Debian 12, Ubuntu 22.04, RHEL 9 and later, and is
 enforced by the Depends line rather than left to fail at exec.
CONTROL

mkdir -p "$OUTDIR"

# **`-Zxz` explicitly, because the default is the *builder's* and that undoes the Depends line
# above on exactly the hosts it was added for.**
#
# Ubuntu's dpkg defaults to zstd (1.22.6 on `ubuntu-latest`, which is where the release builds
# this); Debian's still defaults to xz (1.21.23 on bookworm). Debian 11's dpkg cannot read zstd at
# all, so the same staging tree published from an Ubuntu runner answers
#
#   dpkg-deb: error: archive uses unknown compression for member 'control.tar.zst', giving up
#
# where the xz build answers "loopky depends on libc6 (>= 2.34); however: … 2.31". The first names
# no package and no fix, which is the failure mode the `Depends:` line exists to remove — and it
# lands precisely on the pre-2.34 hosts that line is for. Pinning it also makes the artifact the
# same whoever builds it, rather than something that varies by builder.
#
# xz over gzip only for size: ~16 MB against ~24 for a 64 MB binary.
dpkg-deb -Zxz --build --root-owner-group "$STAGE" "$OUTDIR/loopky_${VERSION}_amd64.deb"
