package com.github.jvsena42.loopky.cli.commands

import com.github.jvsena42.loopky.cli.Args
import com.github.jvsena42.loopky.cli.COMPLETION_SHELLS
import com.github.jvsena42.loopky.cli.CliCommand
import com.github.jvsena42.loopky.cli.CliError
import com.github.jvsena42.loopky.cli.CommandResult
import com.github.jvsena42.loopky.cli.ExitCode
import com.github.jvsena42.loopky.cli.GLOBAL_OPTIONS
import com.github.jvsena42.loopky.cli.OptionValue
import com.github.jvsena42.loopky.cli.cliCommands
import com.github.jvsena42.loopky.cli.result
import com.github.jvsena42.loopky.cli.valueTakingOptions
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * `loopky completion <shell>` — print a completion script for bash, zsh or fish.
 *
 * Generated from [cliCommands] rather than checked in as three files, because a completion that
 * has drifted from the binary is worse than none: it offers a flag that is refused and hides one
 * that works, and neither failure reports itself.
 *
 * Three properties this command is arranged around.
 *
 * **The script goes on stdout, alone, and is meant to be `eval`'d.** That is the same machine
 * channel every other command writes its `--json` to, and it is the reason `completion` is one of
 * the two verbs [com.github.jvsena42.loopky.cli.main] answers *before* Koin starts: it needs no
 * session, no homeserver and no `libpubkycore`, so a host outside the shipped matrix can still
 * install completions, and so nothing about generating a static string can fail on a network.
 *
 * **The update check is off for this verb.** The generated script's intended home is a line in
 * `.bashrc` — `eval "$(loopky completion bash)"` — which puts this command in the path of every
 * new shell. The check is one HTTPS GET, cached for a day and awaited before exit, and a shell
 * that opens a second slower once a day because of a completion script is a bug nobody would
 * trace back to here.
 *
 * **Nothing it emits reaches the network either.** See the note on [OptionValue]: a deck id after
 * `deck show` would be a homeserver round trip on a keypress, which is a tab key that hangs.
 */
fun completion(args: Args): CommandResult {
    val shell = args.word(1) ?: throw CliError(
        ExitCode.Usage,
        "completion needs a shell. One of ${COMPLETION_SHELLS.joinToString(", ")}.",
    )
    val script = when (shell) {
        "bash" -> bashCompletion()
        "zsh" -> zshCompletion()
        "fish" -> fishCompletion()
        else -> throw CliError(
            ExitCode.Usage,
            "no completion for '$shell'. The shells are ${COMPLETION_SHELLS.joinToString(", ")}.",
        )
    }
    // `trimEnd`, because `emit` prints the human channel with `println`: without it the script
    // arrives with a blank line on the end, and `loopky completion zsh > _loopky` writes a file
    // that differs from the one the packagers generate by a byte nobody can see.
    return result(CompletionPayload(shell, script), script.trimEnd())
}

/**
 * The script travels in the `--json` envelope too, because the script *is* the result.
 *
 * A caller that asked for `--json` and got only a shell name back would have to run the command
 * again without it to get the thing it asked for.
 */
@Serializable
private data class CompletionPayload(
    @SerialName("shell") val shell: String,
    @SerialName("script") val script: String,
)

/** How to install each script, printed into it — the one question every user has next. */
private val INSTALL_HINTS = mapOf(
    "bash" to listOf(
        "eval \"\$(loopky completion bash)\"    # in ~/.bashrc",
        "loopky completion bash > /usr/share/bash-completion/completions/loopky   # system-wide",
    ),
    "zsh" to listOf(
        "loopky completion zsh > \"\${fpath[1]}/_loopky\"   # then restart the shell",
        "eval \"\$(loopky completion zsh)\"    # in ~/.zshrc, after compinit",
    ),
    "fish" to listOf(
        "loopky completion fish > ~/.config/fish/completions/loopky.fish",
    ),
)

internal fun header(shell: String): String = buildString {
    appendLine("# loopky $shell completion, generated by `loopky completion $shell`.")
    appendLine("#")
    appendLine("# Regenerate it after upgrading loopky — it describes the surface of the binary")
    appendLine("# that printed it, and a stale copy offers flags that are refused.")
    appendLine("#")
    INSTALL_HINTS.getValue(shell).forEach { appendLine("#   $it") }
}

/** `--name` for every option a command takes, its globals included, as one space-separated word list. */
internal fun optionWords(command: CliCommand): String =
    (command.options + GLOBAL_OPTIONS).map { "--${it.name}" }.distinct().sorted().joinToString(" ")

internal fun globalWords(): String = GLOBAL_OPTIONS.map { "--${it.name}" }.sorted().joinToString(" ")

/**
 * Every option that consumes the next token, `--` prefixed, for the "did the previous word eat
 * this one" test each script makes while it walks the line.
 */
internal fun valueTakingWords(): String = valueTakingOptions().joinToString(" ") { "--$it" }

/** Options grouped by what they accept, so each script writes one arm per kind rather than per name. */
internal fun optionsByValue(): Map<OptionValue, List<String>> =
    (cliCommands().flatMap { it.options } + GLOBAL_OPTIONS)
        .distinctBy { it.name }
        .filter { it.value != OptionValue.Switch }
        .groupBy({ it.value }, { "--${it.name}" })
